#!/usr/bin/env bash

# You can execute me through Glide by doing the following:
# - Execute `glide slow`
# - ???
# - Profit

pushd $GOPATH/src/github.com/appscode/grpc-go-addons

glide up -v
glide vc --use-lock-file --no-tests

popd
